minimum_pre_commit_version: "3.2.0"
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        files: ^\.github/workflows/.*\.ya?ml$
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npm exec -- prettier --check
        language: system
        types_or: [css, html, javascript, json, markdown, ts, yaml]
      - id: project-check
        name: project check
        entry: npm run check
        language: system
        pass_filenames: false
