import "./styles.css";

export { flex, grid, scrollArea, separator, stack } from "./layout";
export {
  bottomPanel,
  dialog,
  loadingRegion,
  sidePanel,
  splitView,
  createSplitViewState,
  setActivePane,
  setPaneCollapsed,
  setPaneSizes,
} from "./workspace";
export {
  alert,
  checkbox,
  dataGrid,
  editableText,
  field,
  form,
  historyTimeline,
  iconButton,
  progress,
  radioGroup,
  segmentedControl,
  sidebar,
  statusIndicator,
  tabs,
  textComponent as text,
  textField,
  themeRoot,
  toolbar,
} from "./components";
export {
  commitFormFields,
  createFormState,
  formStateStatus,
  getFormField,
  setFormDraft,
  setFormErrors,
  setFormStatus,
} from "./form";
export {
  commitDataGridCell,
  createDataGridState,
  getDataGridCell,
  setDataGridClipboard,
  setDataGridSelection,
} from "./data-grid";

export {
  CATALOG_COMPONENTS,
  CATALOG_CONCEPTS,
  CATALOG_GROUPS,
  CATALOG_PAGE_COPY,
  CATALOG_PAGES,
  CATALOG_REGISTRY,
  COMPONENT_IDS,
  COMPONENT_MATRIX_PAGE_COPY,
  COMPONENT_PAGE_COPY,
  COMPONENT_REGISTRY,
  COMPONENT_SOURCE_RECIPES,
  CONCEPT_IDS,
  CONCEPT_REGISTRY,
  PAGE_IDS,
  PHILOSOPHY_PAGE_COPY,
  RUNTIME_COMPONENT_REGISTRY,
  componentDocumentationCopy,
  componentSource,
  defaultProps,
  findRegistryEntry,
  isCatalogComponentId,
  isCatalogPageId,
} from "./catalog/registry";
export { mountCatalog, getMountLabel } from "./catalog/shell";
export {
  parseComponentSelection,
  serializeComponentSelection,
} from "./catalog/state";

export {
  defineIkaSue,
  IKA_ELEMENT_TAGS,
  IKA_TAG_BY_KIND,
  IkaDataGridElement,
  IkaElement,
  IkaHistoryTimelineElement,
  IkaSplitViewElement,
  IkaTabsElement,
  tagNameForKind,
  dataGridQueryForViewport,
} from "./elements";
export { renderIkaView } from "./view";
export { IkaSueError } from "./errors";
export { IKA_ELEMENT_CONTRACTS } from "./abi";
export {
  IKASUE_ABI_VERSION,
  IKA_VIEW_KINDS,
  isIkaDataGridColumn,
  isIkaDataGridEdit,
  isIkaDataGridQuery,
  isIkaDataGridRow,
  isIkaDataGridSelection,
  isIkaError,
  isIkaJsonRecord,
  isIkaJsonValue,
  isIkaMessage,
  isIkaRowPage,
  isIkaRowRequest,
  isIkaSplitViewPane,
  isIkaTabsItem,
  isIkaView,
} from "./contract";

export type {
  AlertOptions,
  AlertSpec,
  BottomPanelOptions,
  BottomPanelSpec,
  CheckboxOptions,
  CheckboxSpec,
  DataGridCell,
  DataGridOptions,
  DataGridSelection,
  DataGridSpec,
  DataGridState,
  DialogOptions,
  DialogSpec,
  EditableTextOptions,
  EditableTextSpec,
  FieldOptions,
  FieldSpec,
  FlexOptions,
  FlexSpec,
  FormField,
  FormOptions,
  FormSpec,
  FormState,
  FormStateStatus,
  GridOptions,
  GridSpec,
  HistoryTimelineOptions,
  HistoryTimelineSpec,
  IconButtonOptions,
  IconButtonSpec,
  LayoutChild,
  LoadingRegionOptions,
  LoadingRegionSpec,
  RadioGroupOptions,
  RadioGroupSpec,
  ScrollAreaOptions,
  ScrollAreaSpec,
  SegmentedControlOptions,
  SegmentedControlSpec,
  SeparatorOptions,
  SeparatorSpec,
  SidePanelOptions,
  SidePanelSpec,
  SidebarOptions,
  SidebarSpec,
  SplitPane,
  SplitViewOptions,
  SplitViewSpec,
  SplitViewState,
  StatusIndicatorOptions,
  StatusIndicatorSpec,
  TabsOptions,
  TabsSpec,
  TextFieldOptions,
  TextFieldSpec,
  TextOptions,
  TextSpec,
  ThemeRootOptions,
  ThemeRootSpec,
  ToolbarOptions,
  ToolbarSpec,
  ProgressOptions,
  ProgressSpec,
} from "./types";
export type {
  IkaDataGridColumn,
  IkaDataGridEdit,
  IkaDataGridQuery,
  IkaDataGridRow,
  IkaDataGridSelection,
  IkaDataGridSpec,
  IkaError,
  IkaJsonPrimitive,
  IkaJsonRecord,
  IkaJsonValue,
  IkaMessage,
  IkaRowPage,
  IkaRowRequest,
  IkaSplitViewPane,
  IkaSplitViewSpec,
  IkaTabsItem,
  IkaTabsSpec,
  IkaView,
  IkaViewKind,
} from "./contract";
export type {
  IkaDataGridViewport,
  IkaElementTagName,
  IkaSueRegistry,
} from "./elements";
export type { IkaElementContract, IkaElementPropertyContract } from "./abi";
export type {
  CatalogComponentId,
  CatalogEntry,
  CatalogLocale,
  CatalogMount,
  CatalogMountOptions,
  CatalogPageId,
} from "./catalog/types";
